root:
  src:  './src'
  dest: './public'

tasks:
  defaultOrder:
    - css
    - images
    - js
  watchableTasks:
    - css
    - images
    - js
    - static

  # BrowserSync
  browserSync:
    server:
      baseDir: './public'

  # CSS Task
  css:
    src: 'scss'
    dest: 'css'
    postcss:
      # postcss-cssnext
      cssnext:
        browsers:
          - 'last 2 versions'
          - 'IE 9'
          - 'iOS 7'
      # postcss-assets
      assets:
        loadPaths:
          - 'fonts/'
          - 'images/'
      # colorguard
      colorguard:
        threshold: '5'
      # cssnano
      cssnano:
        colormin: false
        zindex: false
    extensions:
      - 'css'
      - 'scss'
      - 'sass'

  # Images Task
  images:
    src: 'img'
    dest: 'img'
    extensions:
      - 'png'
      - 'jpg'
      - 'jpeg'
      - 'gif'

  # JS Task
  js:
    src: 'js'
    dest: 'js'

    localAssets:


    vendorSrc: 'vendor'
    vendorAssets:

    extensions:
      - 'js'
      - 'json'

  static:
    src: 'static'
    dest: './'
    extensions:
      - 'html'

    svgSprite:
      src: 'icons'
      dest: 'images'
      extensions:
        - 'svg'

assetTasks:
  - 'fonts'
  - 'images'
  - 'svgSprite'

codeTasks:
  - 'css'
  - 'js'
