root: 
  src:  "./src"
  dest: "./public"

tasks:
  css:
    src: "scss"
    dest: "css"
    postCss:
      autoprefixer:
        browsers: ['last 2 versions', 'IE 9']
      cssnano: 
        convertValues: false
        zindex: false
    extensions: ["sass", "scss", "css"]